config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index', as:'root'
  get '/about', to: 'welcome#about'
  get '/contacts/new', to: 'contacts#new'
  post '/contacts', to:'contacts#thank_you'

  get '/products/new', {to: 'products#new', as: :new_product}
  post '/products', {to: 'products#create'}

  get '/products/:id', {to: 'products#show', as: :show_product}
  get '/products', {to: 'products#index', as: :index}

  delete '/products/:id', to: "products#destroy"

  get '/products/:id/edit', {to: "products#edit", as: :edit_product}
  patch '/products/:id', {to: 'products#update', as: :product}

  post '/products/:product_id/reviews', {to: "reviews#create", as: :product_reviews}
  delete '/products/:product_id/reviews/:id', {to: "reviews#destroy", as: :product_review}
  patch "/reviews/:id/toggle" => "reviews#toggle_hidden", as: "toggle_hidden"

  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  post '/products/:product_id/reviews/:review_id/likes', {to: "likes#create", as: :product_review_likes}
  delete '/products/:product_id/reviews/:review_id/likes/:id', {to: "likes#destroy", as: :product_review_like}

  resources :products do
    resources :favourites, only: [:create, :destroy]
  end

  get '/admin/panel', to: 'administrators#panel'
  get '/favourites', to: 'welcome#favourite'

  resources :news_articles
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :reviews do
    resources :votes, only: [:create, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many(:reviews, dependent: :destroy)
    has_many :favourites, dependent: :destroy
    has_many :users, through: :favourites
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    # .reviews
    # .reviews<<(object, ...)
    # .reviews.delete(object, ...)
    # .reviews.destroy(object, ...)
    # .reviews=(objects)
    # .reviews_singular_ids
    # .reviews_singular_ids=(ids)
    # .reviews.clear
    # .reviews.empty?
    # .reviews.size
    # .reviews.find(...)
    # .reviews.where(...)
    # .reviews.exists?(...)
    # .reviews.build(attributes = {}, ...)
    # .reviews.create(attributes = {})
    # .reviews.create!(attributes = {})
    # .reviews.reload


    validates(:title, presence: true, uniqueness: {case_sensitive: false})
    validates(:description, presence: true, length: {minimum: 10})
    validates(:price, numericality: {greater_than: 0.00, less_than: 1000.00})
    validates(:sales_price, numericality: {less_than_or_equal_to: :price})

    # how to write validation of two columns in one line
    # validates :name, :price, presence:true, uniqueness: {case_sensitive:false}

    def hit # called on an instance
        # self.hit : called on a class
        increment!(:hit_count)
        # self class method
        # @ instance method
    end

    def self.price_range
        where("price > 100.0 AND price < 300.0").order('title asc').limit(5)
    end

    before_destroy(:before_destroy)
    before_validation(:set_default_price_to_1)
    before_validation(:set_deafult_hit_count_to_0)
    before_validation(:capitalize_product_title)
    after_initialize(:sales_price_equal_to_price)
    validate :reserved_name
    before_validation :tag_name

    def tag_name
        self.tags.map {|tag| tag.name}.join(', ')
    end

    def tag_name=(custom_tags)
        self.tags = custom_tags.strip.split(',').map do |tag_name|
            Tag.find_or_initialize_by(name: tag_name)
        end
    end

    private

    def set_default_price_to_1
        self.price ||=1
    end

    def set_deafult_hit_count_to_0
        self.hit_count ||=0
    end

    def capitalize_product_title
        self.title = title.capitalize
    end

    def sales_price_equal_to_price
        self.sales_price ||=price
    end

    def before_destroy
        puts "Product is about to be deleted"
    end

    #custom validation
    scope(:search, -> (product) {where("title ILIKE ? OR description ILIKE ?", "%#{product}%", "%#{product}%")})
    
    def reserved_name
        if title&.downcase&.include?("apple")||title&.downcase&.include?("microsoft")||title&.downcase&.include?("sony")
            self.errors.add(:title, "Reserved Word!")
        end
    end



end

# update_attribute
# What does update_attribute do in ActiveRecord? Give an example. Should it be used or not?
# - update_attribute will change an attribute (user.update_attribute(:name, "Zaiste")) and persist but without running validations
# It shouldn't be used for the sake of the quality of data that you want to collect

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController
    before_action :authenticate_user!, only: [:create, :destroy, :update]
    # rails g controller api/v1/products
    def index
        products = Product.order(created_at: :desc)
        render(json: products, each_serializer: ProductsCollectionSerializer)
    end

    def show
        product = Product.find params[:id]
        render json: product, include: [:seller, {reviews: [:seller]}]
        # render(json: products, each_serializer: ProductsCollectionSerializer)
        # ^ each_serializer only works for a collection of data
        # if you want to use it for a single data, e.g. show page, then just use serializer: <name-of-serializer>
    end

    def create
        product = Product.new product_params
        product.user = current_user
        if product.save
            render json: {id: product.id}
        else
            render json: {errors: product.errors}, status: 422
        end
    end

    def destroy
        product = Product.find params[:id]
        product.destroy
        render json: {status: 200}, status: 200
    end

    def update
        product = Product.find params[:id]
        if product.update product_params
            render json: {id: product.id}
        else
            render json: {errors: product.errors}, status: 422
        end
    end

    private

    def product_params
        params.require(:product).permit(:title, :description, :price)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :product_params, only: [:create, :update]
    before_action :find_product, only: [:show, :edit, :destroy, :update]
    before_action :authenticate_user!, except: [:show, :index]
    before_action :authorize, only: [:destroy, :update, :edit]
    def new
        @product = Product.new
    end

    def create
        flash[:notice] = "Product added!"
        # product_params = params.require(:product).permit(:title, :description, :price, :sales_price)
        @product = Product.new product_params
        @product.user = current_user
        if @product.save
            ProductMailer.new_product(@product).deliver_later
            redirect_to show_product_path(@product)
            # render plain: "product saved!"
        else
            render :new
        end
    end

    def show
        # @product = Product.find params[:id]
        @review = Review.new # instantiates and creates and object of Parameters
        @reviews = @product.reviews.order(created_at: :desc)

         # In this case only the product owner will have all reviews available in the
        # through @reviews (including hidden reviews).
        # You could also remove this logic here and do some logic in the view. Your use case (and
        # for now, the size of your Rails toolset) will determine the best way to things.
        # We've done it this way because with the tools available to us it minimizes the
        # amount of repeated code and if else statements in our view.
        if can? :crud, @product
            @reviews = @product.reviews.order(created_at: :desc)
        else
            @reviews = @product.reviews.where(hidden: false).order(created_at: :desc)
        end
    end

    def index
        if params[:tag]
            @tag = Tag.find_or_initialize_by(name: params[:tag])
            @product = @tag.products.order(created_at: :desc)
        else
            @product = Product.all.order('created_at desc')
        end
    end

    def destroy
        flash[:notice] = "Product deleted!"
        # product = Product.find params[:id]
        @product.destroy
        redirect_to index_path
    end

    def edit
        # @product = Product.find params[:id]
    end

    def update
        # product_params = params.require(:product).permit(:title, :description, :price, :sales_price)
        # @product = Product.find params[:id]
        if @product.update product_params
            flash[:notice] = "Updated!"
            redirect_to show_product_path(@product)
        else
            render :edit
        end
    end

    private

    def product_params
        params.require(:product).permit(:title, :description, :price, :sales_price, :tag_name)#, {tag_ids: []})
    end

    def find_product
        @product = Product.find params[:id]
    end

    def authorize
        redirect_to index_path, alert: "Not Authorized!" unless can?(:crud, @product) 
    end
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
    <ul>
        <% @product.errors.full_messages.each do |errors| %>
            <li><%= errors %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @product do |p| %>
    <div>
        <%= p.label :title%>
        <%= p.text_field :title%>
    </div>
    <div>
        <%= p.label :description%>
        <%= p.text_field :description%>
    </div>
    <div>
        <%= p.label :price%>
        <%= p.text_field :price%>
    </div>
    <div>
        <%= p.label :sales_price%>
        <%= p.text_field :sales_price%>
    </div>
    <div>
        <%#= collection_check_boxes(:product, :tag_ids, Tag.all, :id, :name) %>
        Custom Tags: <%= p.text_field :tag_name%>
    </div>
    <%= p.submit%>
<% end %>

<script>
$('#product_tag_name').selectize({
    delimiter: ',',
    persist: false,
    labelField: 'name',
    valueField: 'name',
    searchField: 'name',
    options: <%= Tag.select(:name).to_json(except: [:id]).html_safe%>,
    create: function(input) {
        return {
            name: input
        }
    }
});
</script>

app/views/products/edit.html.erb
<h1>Edit</h1>

<%= render "form"%>

app/views/products/index.html.erb
<h1>List of Products</h1>

<% @product.each do |items| %>
    <% if params[:tag]%>
        <p class="badge badge-dark"><%= params[:tag]%> tag</p>
    <% end %>
    <h1><%= link_to items.title, show_product_path(items)%></h1>
    <p><%= items.description%></p>
    <p>Price : $<%= items.price %> Sales Price : $<%= items.sales_price%></p>

<% end %>

app/views/products/new.html.erb
<h1>Add New Products!</h1>

<%= render "form"%>

app/views/products/show.html.erb
<h1>Product Name: <%= @product.title%></h1>
<p>Description: <%= @product.description%></p>
<p>Price: <%= @product.price %></p>
<p>Sales Price: <%= @product.sales_price%></p>
<p>created at: <%= @product.created_at%></p>

<p><%= @product.favourites.count %> favourites</p>
<% if can?(:favourite, @product)%>
    <% if @product.favourites.find_by(user: current_user).present? %>
        <%= link_to "💔Un-favourite💔", product_favourite_path(@product, @product.favourites.find_by(user: current_user)), method: :delete %>
    <% else %>
        <%= link_to "❤️Favourite❤️", product_favourites_path(@product), method: :post %>
    <% end %>
<% end %>

<div>Tag:
<%@product.tags.each do |tag|%>
    <p class="badge badge-dark"><%= link_to tag.name, index_path(tag: tag.name) %></p>
<% end %>
</div>


<% if can?(:crud, @product) %>
    <%= link_to "Delete", show_product_path(@product.id), method: :delete, data:{confirm: "Do you want to delete this product?"}%>
    <%= link_to "Edit", edit_product_path(@product)%>
<% end %>



<hr/>

<%= form_with(model: [@product, @review], local: true) do |r| %>
    <% if @review.errors.any? %>
        <ul>
            <% @review.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>

    <div>
        <%= r.label :body%>
        <%= r.text_area :body, placeholder: "How did you like this product?" %>
    </div>
    <div>
        <%= r.label :rating%>
        <%= r.text_field :rating, placeholder: "i.e. 1-5" %>
    </div>
    <%= r.submit%>
<% end %>

<hr/>

<% @reviews.each do |review| %>
    <div class="<%= 'hidden-review' if review.hidden %>">
        <h3>Rating: <%= review.rating %></h3>
        <p>
            <%= review.body %>
        </p> 
        <p>Reviewed by: <%= review.user.full_name %></p>
        <small><%= review.likes.count %> people like this</small>
    </div>

    <%if review.likes.find_by(user: current_user).present? %>
        <%= link_to "Un-like", product_review_like_path(review.product_id, review.id, review.likes.find_by(user_id: current_user.id)), method: :delete %>
    <% else %>
            <%= link_to "Like", product_review_likes_path(review.product_id, review.id), method: :post %>
    <% end %>

    <% if can? :crud, review %>
        <%= link_to 'Delete', product_review_path(review.product_id, review.id), method: :delete, data: { confirm: 'Are you sure that you want to delete this review?' } %>
    <% end %>
    <% if can? :crud, @product %>
        <%= link_to "#{review.hidden ? 'Show' : 'Hide' }", toggle_hidden_path(review), method: :patch %>
    <% end %>
    <br/>
    <% voter = review.votes.find_by(user: current_user) %>
    <% if voter.nil? %>
        <p><%= review.votes.where(upvote: true).count%> upvotes  <%= link_to "👍 Up-Vote", review_votes_path(review, upvote: true), method: :post%></p>
        <p><%= review.votes.where(upvote: false).count%> downvotes  <%= link_to "👎 Down-Vote", review_votes_path(review, upvote: false), method: :post%></p>
    <% else %>
        <p><%= review.votes.where(upvote: true).count%> upvotes  <%= link_to_if voter.upvote == false, "👍 Up-Vote", review_vote_path(review, voter), method: :patch%></p>
        <p><%= review.votes.where(upvote: false).count%> downvotes  <%= link_to_if voter.upvote == true, "👎 Down-Vote", review_vote_path(review, voter), method: :patch%></p>
    <% end %>
  <% end %>