config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index', as:'root'
  get '/about', to: 'welcome#about'
  get '/contacts/new', to: 'contacts#new'
  post '/contacts', to:'contacts#thank_you'

  get '/products/new', {to: 'products#new', as: :new_product}
  post '/products', {to: 'products#create'}

  get '/products/:id', {to: 'products#show', as: :show_product}
  get '/products', {to: 'products#index', as: :index}

  delete '/products/:id', to: "products#destroy"

  get '/products/:id/edit', {to: "products#edit", as: :edit_product}
  patch '/products/:id', {to: 'products#update', as: :product}

  post '/products/:product_id/reviews', {to: "reviews#create", as: :product_reviews}
  delete '/products/:product_id/reviews/:id', {to: "reviews#destroy", as: :product_review}
  patch "/reviews/:id/toggle" => "reviews#toggle_hidden", as: "toggle_hidden"

  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

  post '/products/:product_id/reviews/:review_id/likes', {to: "likes#create", as: :product_review_likes}
  delete '/products/:product_id/reviews/:review_id/likes/:id', {to: "likes#destroy", as: :product_review_like}

  resources :products do
    resources :favourites, only: [:create, :destroy]
  end

  get '/admin/panel', to: 'administrators#panel'
  get '/favourites', to: 'welcome#favourite'

  resources :news_articles
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :reviews do
    resources :votes, only: [:create, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products
      resource :session, only: [:create, :destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to 'Home', root_path%> | 
    <%= link_to 'About', about_path%> | 
    <%= link_to 'Contact Us', contacts_new_path%> | 
    <%= link_to 'New Product', new_product_path%> |
    <%= link_to 'All Products', index_path%> |

    <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'Admin Page', admin_panel_path%> |
    <% else %>
      <p class="admin"><%= link_to 'Admin Page', admin_panel_path%></p>
    <% end %>

    <%= flash[:notice] || flash[:alert] %>

    <% if user_signed_in? %>
      <%= link_to "My Favourites", favourites_path%>
      <div>Welcome, <%= current_user.full_name%></div>
      <%= link_to "Sign Out", sessions_path, method: :delete, data: {confirm: "Are you sure you want to sign out?"} %>
    <% else %>
      <%= link_to "Sign In", new_sessions_path %> |
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <hr>
    <%= yield %>
  </body>
</html>